minecraft = "1.21.5"
modloader = "fabric"

[[mods]]
mod_id = "fabric-api"
source = "modrinth"

[[mods]]
mod_id = "lithium"
source = "modrinth"

[[mods]]
mod_id = "sodium"
source = "modrinth"

[[mods]]
mod_id = "controlify"
source = "modrinth"

[[mods]]
mod_id = "custom-mod"
url = "https://github.com/youruser/yourrepo/releases/download/v1.0.0/custom-mod.jar"
